# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracticeUI

	pod 'Floaty', '~> 4.2.0'
	pod 'JJFloatingActionButton'

end
